name: Integration Tests

on:
  push:
    branches:
      - main
  pull_requests:
    branches:
      - main

jobs:
  integration-test:
    env:
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: password
      PGPORT: 5432
      PGDATABASE: music_library_test
    services:
      postgres:
        image: postgres
        env: 
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:3000
    runns-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      -  run: npm ci
      -  run: npm test