name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    env:
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: password
      PGPORT: 5432
      PGDATABASE: music_library_test
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:3000
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      -  run: npm ci
      -  run: npm test
  
      # - name: Install PostgreSQL client
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install --yes postgresql-client
      # - name: Create Database
      #   run: psql $DATABASE_URL -c 'CREATE DATABASE music_library;'
      # - name: Install Dependencies
      #   run: npm ci
      # - name: Run Integration Tests
      #   run: npm test